version: '3.8'
services:
  app:
    build:
      context: ./server  # Spécifier le contexte de build comme le dossier server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app  # Monter le dossier server du hôte vers le dossier de travail dans le conteneur
    environment:
      DatabaseUrl: development
